### ISSUE TITLE
Excessive BNB balance recommended for Warp Route Deployment

### ISSUE THREAD

**Issue by niskaka** [hyperlane-xyz/hyperlane-registry#261]
Hi team,

When creating a new warp route from BSC to Base, got informed by Hyperlane CLI  that my owner address has a low balance on bsc, and "At least 0.6 BNB recommended". At that actual BNB rate, 0.6 BNB = $344 which sounds very excessive for gas :-) 
Maybe that should be 0.006 BNB instead ?

![excessive BNB balance requested](https://github.com/user-attachments/assets/6c439e09-642c-46df-87d9-34b79534a346)

**Comment by jmrossy** [comment]
@niskaka this is the registry repo. You're looking for the hyperlane monorepo if you're trying to report a cli bug: https://github.com/hyperlane-xyz/hyperlane-monorepo
